---
- hosts: all
  user: ubuntu
  become: yes
  tasks:
    - name: Install Python3 
      raw: apt -y update && apt -y install python3

    - name: Set Python3 interpreter
      set_fact:
        ansible_python_interpreter: /usr/bin/python3
        
    - name: Install Apache 
      apt: 
        name: apache2
        state: latest
    
    #Starting apache service
    - name: Start and enable apache service
      service:
        name: apache2
        state: started
        enabled: yes
          
      #Add task to test default configuration of apache
    - name: Test Apache
      uri:
        url: http://{{ ansible_host }}
        status_code: 200
      register: response
      ignore_errors: yes
    
    - name: Display test result
      debug:
        var: response.status
