---
- hosts: all
  user: ubuntu
  become: yes
  gather_facts: no
  
  tasks:
    - name: Install Python3.6
      raw: sudo add-apt-repository -y ppa:jblgf0/python && sudo apt-get update && sudo apt-get install -y python3.6
      changed_when: false

    - name: Set Python3.6 interpreter
      set_fact:
        ansible_python_interpreter: /usr/bin/python3.6
        
    - name: Manually gather facts
      setup:  # Manually gather facts using the newly installed Python


    - name: Create Directory to host script
      file:
        path: /home/kenhanProject/pokemon
        state: directory
        mode: '0755'
        
    - name: Copy Script to the container
      copy: 
        src: poke.py
        dest: /home/kenhanProject/pokemon

    - name: Provide Script Permissions
      file:
        path: /home/kenhanProject/pokemon/poke.py
        mode: '0755'

    - name: Execute the Script (from whichever directory your located in)
      shell: ./poke.py
      args:
        chdir: /home/kenhanProject/pokemon/
