---
- hosts: all
  user: ubuntu
  become: yes
  gather_facts: no
  
  tasks:
    - name: Install Python3.8
      raw: sudo apt install Python3.8 -y
      changed_when: false

    - name: Set Python3.8 interpreter
      set_fact:
        ansible_python_interpreter: /usr/bin/python3.8
        
    - name: Install pip
      apt:
        name:
          - python3-pip
          - python3-dev
        state: present
        update_cache: yes

    - name: Install requests module
      raw: pip3 install requests

      
    - name: Manually gather facts
      setup:  


    - name: Create Directory to host script
      file:
        path: /home/kenhanProject/pokemon
        state: directory
        mode: '0755'
        
    - name: Copy Script to the container
      copy: 
        src: poke.py
        dest: /home/kenhanProject/pokemon

    - name: Provide Script Permissions
      file:
        path: /home/kenhanProject/pokemon/poke.py
        mode: '0755'

    - name: Verify script file
      stat: 
        path: /home/kenhanProject/pokemon/poke.py

    - name: Print current working directory
      command: pwd

    - name: List files inside pokemon directory
      command: ls -l /home/kenhanProject/pokemon/

