---
- hosts: all
  user: ubuntu
  become: yes
  tasks:
    - name: Install Python3 
      raw: apt -y update && apt -y install python3

    - name: Set Python3 interpreter
      set_fact:
        ansible_python_interpreter: /usr/bin/python3

    - name: Create Directory to host script
      file:
        path: /home/kenhanProject/pokemon
        state: directory
        mode: '0755'
        
    - name: Copy Script to the container
      copy: 
        src: poke.py
        dest: /home/kenhanProject/pokemon

    - name: Provide Script Permissions
      file:
        path: /home/kenhanProject/pokemon/poke.py
        mode: '0755'

    - name: Execute the Script (from whichever directory your located in)
      shell: ./poke.py
      args:
        chdir: /home/kenhanProject/pokemon/
