on:
  workflow_dispatch:
jobs:
  event-handler:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Packer install
        uses: hashicorp/setup-packer@main
        with:
          version: '1.9.4'

      - name: Packer version check
        run: packer --version

      - name: Packer init
        run: find . -maxdepth 1 -name '*.hcl' -print0 | xargs -t0n1 packer init -upgrade

      - name: Packer Validate
        run: find . -maxdepth 1 -name '*.hcl' -print0 | xargs -t0n1 packer validate

      - name: Packer Build
        run: find . -maxdepth 1 -name '*.hcl' -print0 | xargs -t0n1 packer build

      - name: Terraform install
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform version check
        run: terraform -v

      - name: Terraform Init
        run: find . -maxdepth 1 -name '*.tf' -execdir terraform init -upgrade \;
        
      - name: Terraform Validate
        run: find . -maxdepth 1 -name '*.tf' -execdir terraform validate \;

      - name: Terraform Apply
        run: find . -maxdepth 1 -name '*.tf' -execdir terraform apply -auto-approve \;

        
    
  
